# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_active',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
