# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now=True)),
                ('is_present', models.BooleanField(default=False)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
    ]
